### PR TITLE
fix: make the endpoint public

### LINKED ISSUE #4: Use GRAASP_ACTOR to allow the seach for public users
If we take a look at this file https://github.com/graasp/graasp-plugin-public/blob/main/src/services/item/service-api.ts
We never use `member` but use a dummy Graasp Actor to perform the task. 

Since the implementation already takes into account the published tag, it shouldn't require much changes, but we should be careful the plugin doesn't give more rights than necessary (eg. the user shouldn't be able to read private items).

### PR DESCRIPTION
**Pull request by louisewang1**
close #4 

Use GRAASP_ACTOR to make endpoints public

- I use the same way as categories (import the public plugin repo). Initially I want to use the options method, but encountered some errors, so I do the same way as plugin-categories. Now it's working well locally.

### CODE REVIEW

File: src/plugin.ts [hunk 1]
```diff
@@ -32,12 +42,12 @@ const plugin: FastifyPluginAsync<GraaspSearchPluginOptions> = async (fastify, op
   fastify.get<{ Params: { keyword: string, range: string }; }>(
     '/search/:range/:keyword',
     { schema: search },
-    async ({ member, params: { keyword, range }, log }) => {
-      const task = getTaskByRange(member, keyword, range);
+    async ({ params: { keyword, range }, log }) => {
+      const task = getTaskByRange(graaspActor as Member, keyword, range);
```
Comment (pyphilia) [inline src/plugin.ts]: It's better to change your task to accept Actor instead.

**Review by pyphilia — CHANGES_REQUESTED** [review]

**Review by pyphilia — APPROVED** [review]
